### ISSUE TITLE
Cloud not start container

### ISSUE THREAD

**Issue by yangkghjh** [mregni/EmbyStat#1132]
# Cloud not start container

**Describe the bug**
Cloud not start container

**To Reproduce**

1. Setup a container on unriad with image uping/embystat:beta-ubuntu-x64
2. It won't start

**System (please complete the following information):**

- OS:  Unraid
- Browser chrome
- Version uping/embystat:beta-ubuntu-x64

**Additional context**

logs:

```
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

**Comment by n00b42** [comment]
Have the same issue/error on Synology/Xpenology.

Also tried nightly, but there I got a NullReferenceException when trying to start it.

**Comment by sfrode** [comment]
It seems that all files are moved from _/app_ to _/app/ubuntu-x64_ in the docker builds for _embystat:ubuntu-x64_. Not sure if that was intentional or not, but you can fix it by overriding the _WORKDIR_ on launch with "-w".

Do note that you have to make additional modifications if you want the database and configuration files outside of your container. The volume does not work as the files are all stored in _/app/ubuntu-x64_.

**Comment by mregni** [comment]
I just uploaded a new beta version, can you check if that's still the problem? If so, I will need to check why the folder changed to /app/ubuntu-x64

**Comment by sfrode** [comment]
Beta 17; no changes.

Here's my docker-compose file that sorts out the launch problem:

```yaml
version: '2'
services:
  embystats:
    image: uping/embystat:beta-ubuntu-x64
    container_name: embystats
    working_dir: /app/ubuntu-x64
    volumes:
      - ./app/config:/app/config:rw
    ports:
      - "6555:6555"
    restart: "unless-stopped"
```

Application files are still under /app/ubuntu-x64 in the container. I did not notice any changes to where the database/config is stored neither.

PS! Thanks for the faster-than-lightning response!
