### ISSUE TITLE
Images not loading in Docker setup with Jellyfin

### ISSUE THREAD

**Issue by stephanrenggli** [mregni/EmbyStat#1642]
# Bug report

**Describe the bug**
Due to the way images/thumbnails are loaded, they can not be loaded if an internal IP/DNS name is used to specify the Jellyfin server.

**To Reproduce**

1. Set up Jellyfin and EmbyStat via docker-compose
1. Run first run setup in EmbyStat and set up Jellyfin server via internal docker DNS name (ex. jellyfin:8086, this will resolve via internal docker DNS)
1. Load any page with images/thumbnails
2. Thumbnails don't load

**Expected behavior**
I would expect images/thumbnails to load correctly. However since Jellyfin is seen to be available at `jellyfin:8086` and not a publicly available domain like `jellyfin.mydomain.com` resources can't be loaded.

Maybe EmbyStat could load all of these resources from Jellyfin first and then the Client loads the resources from EmbyStat and not via API from Jellyfin.

Example docker compose to achieve this setup:
```yaml
version: "2.3"
services:

  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    restart: always
    ports:
      - 8096:8096
    networks:
      - proxy

  embystat:
    container_name: embystat
    image: lscr.io/linuxserver/embystat
    restart: always
    ports:
      - 6555:6555
    networks:
      - proxy
```

**Screenshots**
![Capture](https://user-images.githubusercontent.com/5135902/137562028-daec02c7-2d5f-4ba5-aee7-5e299596695e.PNG)
![Capture](https://user-images.githubusercontent.com/5135902/137562817-3e8501d1-93df-4203-b54a-f4e291c216ae.PNG)

Obviously `jellyfin:8086` can't be resolved from my client because this is the docker internal DNS name.

**System (please complete the following information):**

- OS: Ubuntu -> Docker
- Browser: Chrome
- Version: 0.2.0-beta.27
- Media server type: Jellyfin
