### ISSUE TITLE
Docker beta/nightly linux

### ISSUE THREAD

**Issue by jaketame** [mregni/EmbyStat#310]
Problem:
Using either beta-linux or nightly-linux on docker it errors

Docker Logs Error:
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

**Comment by mregni** [comment]
With what command did you start the linux nightly container?
Because I'm able to run the nightly build, beta build is crashing indeed.

![image](https://user-images.githubusercontent.com/22617019/51909807-cc0a3680-23cd-11e9-89b8-700291879a61.png)

I'll have a look why it is failing

**Comment by jaketame** [comment]
I'm using compose

```
  stats:
   image: uping/embystat:nightly-linux
   container_name: stats
   restart: unless-stopped
   networks:
    - web
   volumes:
    - /opt/apps/embystats/:/app
   environment:
    - TZ=Europe/London
    - UID=1001
    - GID=1001
   labels:
    traefik.enable: "true"
    traefik.backend: "stats"
    traefik.port: "5432"
    traefik.frontend.redirect.entryPoint: "https"
```
